Do firmware download at early stage

diff --git a/bootstrap-minimal b/bootstrap-minimal
--- a/bootstrap-minimal
+++ b/bootstrap-minimal
@@ -190,6 +190,28 @@ if is_host_arm; then
     apt-get -y -qq install qemu-user-static binfmt-support
 fi
 
+# Download firmware
+if [ -d ${BUILD_DIRECTORY}/firmware ]; then
+    if [ -d ${BUILD_DIRECTORY}/firmware/.git ]; then
+        echo "Updating to latest firmware"
+        cd ${BUILD_DIRECTORY}/firmware
+        git pull
+	else
+		echo "WARNING: Firmware directory exists but it is not a git repository."
+		echo "         Nothing done."
+	fi
+else
+    echo "Downloading latest firmware"
+    cd ${BUILD_DIRECTORY}
+    git clone https://github.com/raspberrypi/firmware.git
+    if [ $? -ne 0 ]; then
+        do_unmount_partitions
+        do_unset_partitions
+        echo "Error: failed to download firmware repository."
+        exit 1
+    fi
+fi
+
 if [ -z "${TARGET_DEVICE}" ]; then
     do_create_image
 fi
@@ -240,28 +262,6 @@ fi
 mount -t proc proc ${CHROOT_DIR}/proc
 mount -t sysfs sysfs ${CHROOT_DIR}/sys
 mount -o bind /dev ${CHROOT_DIR}/dev
-
-# Download firmware
-if [ -d ${BUILD_DIRECTORY}/firmware ]; then
-    if [ -d ${BUILD_DIRECTORY}/firmware/.git ]; then
-        echo "Updating firmware"
-        cd ${BUILD_DIRECTORY}/firmware
-        git pull
-	else
-		echo "WARNING: Firmware directory exists but it is not a git repository."
-		echo "         Nothing done."
-	fi
-else
-    echo "Downloading latest firmware"
-    cd ${BUILD_DIRECTORY}
-    git clone https://github.com/raspberrypi/firmware.git
-    if [ $? -ne 0 ]; then
-        do_unmount_partitions
-        do_unset_partitions
-        echo "Error: failed to download firmware repository."
-        exit 1
-    fi
-fi
 
 sudo cp -R ${BUILD_DIRECTORY}/firmware/hardfp/opt/* ${CHROOT_DIR}/opt/
 sudo cp -R ${BUILD_DIRECTORY}/firmware/modules/* ${CHROOT_DIR}/lib/modules/
