Update build-asterisk

diff --git a/build-asterisk b/build-asterisk
--- a/build-asterisk
+++ b/build-asterisk
@@ -12,6 +12,24 @@ do_download_asterisk() {
     rm /usr/src/certified-asterisk-${ASTERISK_VERSION}.tar.gz
 }
 
+do_make_asterisk()
+{
+    echo "Installing prerequisites."
+    apt-get -y -qq update
+    apt-get install -y -qq git-core build-essential libsqlite3-dev libxml2-dev libncurses5-dev libncursesw5-dev libiksemel-dev libssl-dev libeditline-dev libedit-dev curl libcurl4-gnutls-dev
+    if [ $? -ne 0 ]; then
+        echo "Error: Could not install prerequisites."
+        exit 1
+    fi
+    
+    cd /usr/src/certified-asterisk-${ASTERISK_VERSION}
+    /usr/src/certified-asterisk-${ASTERISK_VERSION}/bootstrap
+    ./configure
+    
+    make menuselect
+    
+}
+
 do_package_config() {
     [ -d /usr/src/certified-asterisk-config-${ASTERISK_VERSION} ] && rm -rf /usr/src/certified-asterisk-config-${ASTERISK_VERSION}
     
@@ -53,3 +71,4 @@ EOF
 
 do_download_asterisk
 do_package_config
+do_make_asterisk
